# Generated by Django 5.1 on 2024-08-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Пост'},
        ),
    ]
